version: "3"

services:

  guacd.rdp.local:
    image: guacamole/guacd
    restart: always
    volumes:
      - ./files/guacd:/drive:rw
      - ./files/guacd/record:/record:rw

  guacamole.rdp.local:
    image: guacamole/guacamole
    restart: always
    volumes:
      - /root/files/web2:/usr/local/apache2/htdocs:ro
    environment:
      GUACD_HOSTNAME: 'guacd.rdp.local'
      GUACD_PORT: 4822
      MYSQL_HOSTNAME: 'mysql.rdp.local'
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwe123'

  mysql.rdp.local:
    image: mysql
    restart: always
    volumes:
      - ./files/mysql/db:/var/lib/mysql
      - ./files/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: 'guacamole_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'qwe123'
      MYSQL_ROOT_PASSWORD: 'qwe123'

  reverseproxy.rdp.local:
    image: nginx
    volumes:
      - ./files/reverseproxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/reverseproxy/ssl:/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
